### ISSUE TITLE
cannot install self written XPI

### ISSUE THREAD

**Issue by 3052** [mozilla-mobile/firefox-android#6087]
I wrote my own extension, here:

https://github.com/3052/umber/tree/main/extension

I cannot install this extension. I tried this instruction:
Settings > About Fennec. Tap the logo five times to unlock the debug menu, then there will be an option to install addons from a file.

but it says:

this add-on could not be installed because it has not been verified

**Comment by onemahon** [comment]
Note: this repository is no longer maintained, we have moved Firefox for Android to Mozilla Central. Please refer to our migration announcement [here](https://github.com/mozilla-mobile/firefox-android/wiki), and if you'd like to submit a bug, please open it in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Fenix). Thanks!
